runtime: python37
entrypoint: gunicorn -b :$PORT main:app

instance_class: F1
automatic_scaling: 
  max_instances: 1

env_variables:
  PRODUCTION_ENV: "production"

handlers:
  - url: /api/(.*)
    script: auto
    secure: always
    redirect_http_response_code: 301
  - url: /(.*\.(gif|media|json|ico|eot|ttf|woff|woff2|png|jpg|css|js))$
    static_files: build/\1
    upload: build/(.*)
    secure: always
    redirect_http_response_code: 301
  - url: /(.*)
    static_files: build/index.html
    upload: build/index.html
    secure: always
    redirect_http_response_code: 301