export const themes = [
    {
        headerBackgroundColor: "#eaeae8",
        indexColumnBackgroundColor: "#eaeae8",
        mainBackgroundColor: "#ffffff",
        borderColor: "#684c37",
        courseFontColor: "#000000",
        courseBackgroundColor: {
            必修: "#cdc0a6",
            體育: "#e5ddc6",
            軍訓: "#c3aa8e",
            外語: "#f2ded5",
            通識: "#ddbda8",
            選修: "#e3cea7",
        },
    },
    {
        headerBackgroundColor: "#eaeae8",
        indexColumnBackgroundColor: "#eaeae8",
        mainBackgroundColor: "#ffffff",
        borderColor: "#000000",
        courseFontColor: "#000000",
        courseBackgroundColor: {
            必修: "#dadbc9",
            體育: "#e5ddc6",
            軍訓: "#b6b4bf",
            外語: "#dad2c5",
            通識: "#c1b59d",
            選修: "#b1b3a6",
        },
    },
    {
        headerBackgroundColor: "#eaeae8",
        indexColumnBackgroundColor: "#eaeae8",
        mainBackgroundColor: "#ffffff",
        borderColor: "#000000",
        courseFontColor: "#000000",
        courseBackgroundColor: {
            必修: "#8e958e",
            體育: "#e8d8bf",
            軍訓: "#f4ebdc",
            外語: "#babdb4",
            通識: "#eeceb7",
            選修: "#e0d9bd",
        },
    },
    {
        headerBackgroundColor: "#e0ddd6",
        indexColumnBackgroundColor: "#e0ddd6",
        mainBackgroundColor: "#ffffff",
        borderColor: "#6b503b",
        courseFontColor: "#000000",
        courseBackgroundColor: {
            必修: "#d3c3b1",
            體育: "#a2a790",
            軍訓: "#9c8a7c",
            外語: "#838366",
            通識: "#c1c8ab",
            選修: "#ddd9b6",
        },
    },
    {
        headerBackgroundColor: "#eaeae8",
        indexColumnBackgroundColor: "#eaeae8",
        mainBackgroundColor: "#ffffff",
        borderColor: "#000000",
        courseFontColor: "#ffffff",
        courseBackgroundColor: {
            必修: "#cba49d",
            體育: "#deb49c",
            軍訓: "#adb4cc",
            外語: "#a0aaa2",
            通識: "#c0d0c5",
            選修: "#e8cd94",
        },
    },
];
