# Generated by Django 3.1.5 on 2021-02-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('ename', models.CharField(max_length=200)),
                ('ayc', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('cos_id', models.CharField(max_length=50)),
                ('perm_id', models.CharField(max_length=50)),
                ('english', models.BooleanField()),
                ('credit', models.FloatField()),
                ('hours', models.FloatField()),
                ('time', models.CharField(max_length=100)),
                ('num_limit', models.IntegerField()),
                ('reg_number', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=50)),
                ('memo', models.TextField()),
            ],
        ),
    ]
