# Generated by Django 3.1.5 on 2021-05-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_feedback_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='anonymous',
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
