# Generated by Django 3.1.5 on 2021-02-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210211_0230'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('ayc', 'sem', 'cos_id')},
        ),
    ]
