import os


class Configs:
    DEBUG = False
    SECRET_KEY = os.urandom(24)
    SQLALCHEMY_ECHO = False
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_DATABASE_URI = ''
    NCTU_OAUTH_CLIENT_ID = ''
    NCTU_OAUTH_CLIENT_SECRET = ''
    NCTU_OAUTH_REDIRECT_URL = ''
    COURSE_FILE_ROOT = ''