# Generated by Django 3.1.5 on 2021-01-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletin',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='bulletin',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='category',
            field=models.IntegerField(choices=[(0, '通知'), (1, '更新'), (2, '錯誤'), (3, '修復')]),
        ),
    ]
