# Generated by Django 3.1.5 on 2021-01-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210126_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
