# Generated by Django 3.2.13 on 2023-02-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210519_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='last_updated_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
