# Generated by Django 3.1.5 on 2021-02-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210126_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
