name: release
on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - uses: borales/actions-yarn@v4
        with:
          cmd: --cwd frontend install --frozen-lockfile

      - uses: borales/actions-yarn@v4
        with:
          cmd: --cwd frontend build

      - name: Tar files
        working-directory: ./frontend
        run: tar -zcvf build.tar.gz build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend_build
          path: frontend/build.tar.gz
